//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Category
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Category()
    {
        this.Product = new HashSet<Product>();
    }

    public int c_ID { get; set; }
    public string c_Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Product { get; set; }
}

public partial class Customer
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customer()
    {
        this.Visa = new HashSet<Visa>();
    }

    public string cust_Name { get; set; }
    public string cust_Email { get; set; }
    public string cust_Password { get; set; }
    public string cust_ConfarmPassword { get; set; }
    public string cust_Phone { get; set; }
    public string cust_Address { get; set; }
    public string cust_Quistion { get; set; }
    public string cust_Answer { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Visa> Visa { get; set; }
}

public partial class Order_Details
{
    public long Id { get; set; }
    public int O_id { get; set; }
    public int p_id { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<decimal> Total { get; set; }
    public Nullable<decimal> Price { get; set; }
}

public partial class Orders
{
    public int Id { get; set; }
    public Nullable<int> order_Quntaty { get; set; }
    public Nullable<decimal> order_Total { get; set; }
    public Nullable<System.DateTime> order_Date { get; set; }
    public string order_Address { get; set; }
    public string City { get; set; }
    public string Street { get; set; }
    public string UserName { get; set; }
}

public partial class Product
{
    public int p_ID { get; set; }
    public string p_Name { get; set; }
    public int p_Price { get; set; }
    public int p_Quantity { get; set; }
    public int c_ID { get; set; }

    public virtual Category Category { get; set; }
}

public partial class Visa
{
    public int v_No { get; set; }
    public string Email { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public Nullable<int> Zip_Code { get; set; }
    public Nullable<int> Exp_Year { get; set; }
    public string Exp_Month { get; set; }
    public Nullable<int> CVV { get; set; }
    public string Card_Number { get; set; }
    public string Name_On_Card { get; set; }
    public string c_Name { get; set; }

    public virtual Customer Customer { get; set; }
}
