//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class ShipeEntities : DbContext
{
    public ShipeEntities()
        : base("name=ShipeEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Category> Category { get; set; }
    public virtual DbSet<Customer> Customer { get; set; }
    public virtual DbSet<Orders> Orders { get; set; }
    public virtual DbSet<Product> Product { get; set; }
    public virtual DbSet<Order_Details> Order_Details { get; set; }
    public virtual DbSet<Visa> Visa { get; set; }
}
